### ISSUE TITLE
Move "command on x alts detected" setting to commands.yml

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1035]
```yml
        # Threshold of the other accounts command, a value less than 2 means disabled.
        otherAccountsCmdThreshold: 0
        # Command to run when a user has more accounts than the configured threshold.
        # Available variables: %playername%, %playerip%
        otherAccountsCmd: 'say The player %playername% with ip %playerip% has multiple accounts!'
```

This could be moved to the commands.yml file and would allow to define multiple cases when a command should be run.

- Create a class extending `Command` with an additional field to specify the number of alts required before the command is run
- Add setting to the commands.yml config files
- Add migration for moving the above setting to commands.yml
