### ISSUE TITLE
Add option to disable fly status saving.

### ISSUE THREAD

**Issue by Mabus13** [AuthMe/AuthMeReloaded#1036]
### What behaviour is observed:
Fly status saved. But I not need it.

### What behaviour is expected:
I want use /fly playername. And after exit and in playername he must not have fly.

### AuthMe build number:
1492

**Comment by Mabus13** [comment]
Thank you, and wait version with that feature.  ^_^ You guys the best!

**Comment by Mabus13** [comment]
Up. =) Hope  you make possible off saving soon. ^_^

**Comment by ljacqu** [comment]
Wouldn't this solve it? In commands.yml:

```yaml
onLogin:
    noFly:
        command: 'fly %p off'
        executor: 'CONSOLE'
```

**Comment by Mabus13** [comment]
I will try it. Thank you. =)

**Comment by ljacqu** [comment]
Thanks, I look forward to your response :)

**Comment by Mabus13** [comment]
Yes it help, but now all users when in be saw msg about disabling fly.... It can be anoying but anyway for tempoary solution it excelente! THANK YOU again. 
Anyway in best way can add useability to control saving or not fly, op and speed statuses...

**Comment by Mabus13** [comment]
Also i saved in files, when i have SQL... files.... when have sql.... ohhh it realy anoying.

**Comment by ljacqu** [comment]
(alphabetically) hi @DNx5 @Gnat008 @Eufranio @Mabus13 @sgdc3 @Twonox, pardon the disturbance.

As said in #1113 I think we can make it configurable how each property on the limbo player should be handled. I would be very thankful for naming suggestions and guidance on what is useful for plugin users.

I propose something like this:

```yaml
limbo:
  # Options: RESTORE = keep fly status, DISABLE = always disable, ENABLE = always enable
  flyStatus: RESTORE
  # Options: RESTORE = keep to current value, DEFAULT = reset to default
  flySpeed: RESTORE
  # Options: RESTORE = keep to current value, DEFAULT = reset to default
  walkSpeed: RESTORE
```

**Comment by sgdc3** [comment]
sounds good

**Comment by ljacqu** [comment]
Hi @Mabus13 , this is now available with build n. 1611 and above — http://ci.xephi.fr/job/AuthMeReloaded/
Once you start the plugin new options will appear in your config.yml:
```yml
limbo:
    # [...]
    # Whether the player is allowed to fly: RESTORE, ENABLE, DISABLE.
    # RESTORE sets back the old property from the player.
    restoreAllowFlight: 'RESTORE'
    # Restore fly speed: RESTORE, DEFAULT, MAX_RESTORE, RESTORE_NO_ZERO.
    # RESTORE: restore the speed the player had;
    # DEFAULT: always set to default speed;
    # MAX_RESTORE: take the maximum of the player's current speed and the previous one
    # RESTORE_NO_ZERO: Like 'restore' but sets speed to default if the player's speed was 0
    restoreFlySpeed: 'MAX_RESTORE'
    # Restore walk speed: RESTORE, DEFAULT, MAX_RESTORE, RESTORE_NO_ZERO.
    # See above for a description of the values.
    restoreWalkSpeed: 'MAX_RESTORE'
```

Could I ask you to give us some quick feedback whether this corresponds to your expectations or if there's still something that we should do?
