### ISSUE TITLE
Essentials MOTD is ran before login 

### ISSUE THREAD

**Issue by Eufranio** [AuthMe/AuthMeReloaded#1042]
I would like that you guys delay a bit the Essentials MOTD command, like 1 second or so, it is ran before the player actually login, then the logged in message shows after the MOTD...

**Comment by ljacqu** [comment]
This is basically the opposite of the request in #935 :P

**Comment by Eufranio** [comment]
You guys could create a expression in the commands.yml file. That way, it would be:
```
onLogin:
    welcome:
        delay 1 second|wait 1 second|wait 1s|wait 1sec
        command: 'motd'
        executor: 'PLAYER'
```

Then you could remove the config that runs the Essentials motd on join from the main config.
