### ISSUE TITLE
[Feature request] Add "onLogout" into commands

### ISSUE THREAD

**Issue by Jamaic230** [AuthMe/AuthMeReloaded#1218]
With "onLogout" in commands you can do neat stuff like:
```
 onLogin:
   pex_promote:
     command: 'pex promote %p authme'
     executor: CONSOLE
 onLogout:
   pex_demote:
     command: 'pex demote %p authme'
     executor: CONSOLE
```
This will allow you to have a better control of player's permissions.

With this feature you can do other handy stuff to them, like teleporting them to login world/region, setting appropriate game-mode, etc.
