### ISSUE TITLE
PermissionEx with unLoggedInGroup

### ISSUE THREAD

**Issue by xcamnhamx** [AuthMe/AuthMeReloaded#1265]
### What behaviour is observed:
What happened?
- So I enabled the AuthMe function : move unloggedin players to an unloggedin group before they login. But when I add two groups for a player in PermissionsEx, it will auto put the player in one of the groups but not both after their login.

### What behaviour is expected:
- I expected the player to have 2 groups after login.

### Steps/models to reproduce:
1. /pex user (name) group add Donor
2. /pex user (name) group add Moderator
3. Restart server or ask the player to relog.
4. Result

### Plugin list:
This can be found by running `/pl`
I am pretty sure it is caused by AuthMe as I disabled the function and it worked fine.

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Spigot 1.9.4 

### AuthMe build number:
This can be found by running `/authme version`
AuthMeReloaded v5.2 (build: 1542)

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)
-None-

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by ljacqu** [comment]
Hi @xcamnhamx, thanks for the report. The fix by @sgdc3 is available as of build n. 1723 at http://ci.xephi.fr/job/AuthMeReloaded/ . Could you give us some feedback whether this resolves your issue? Thanks

**Comment by xcamnhamx** [comment]
You're welcome. I installed it and configured it to enable the unLoggedInGroup. But now there's another problem, the player's prefix will reverse everytime he relogs. For example: X player has Donor and Moderator. He now has the Moderator prefix, after he left the server and joined back the server, his prefix will be Donor. When he relogs again, he will have Moderator again.

**Comment by sgdc3** [comment]
lol something is not right there xD

**Comment by sgdc3** [comment]
what happens with 3 groups? does it cycle thru the groups or it goes randomly?

**Comment by ljacqu** [comment]
![test](https://user-images.githubusercontent.com/8417009/27988728-a93338a6-6429-11e7-91c5-8b135ba02d89.png)
Hmm, my groups are doubled

**Comment by ljacqu** [comment]
Using LuckPerms 3.2.16 and the config below I get some interesting behavior.

```yml
GroupOptions:
    # Enables switching a player to defined permission groups before they log in.
    # See below for a detailed explanation.
    enablePermissionCheck: true
    # This is a very important option: if a registered player joins the server
    # AuthMe will switch him to unLoggedInGroup. This should prevent all major exploits.
    registeredPlayerGroup: 'unloggedin'
    # Similar to above, unregistered players can be set to the following
    # permissions group
    unregisteredPlayerGroup: ''
```

![capture3](https://user-images.githubusercontent.com/8417009/27988816-88b2d354-642c-11e7-8032-94a9cb91127a.PNG)

^ My groups (captain, lieutenant) are duplicated, and I get the unloggedin group on login? I'm confused.

The duplication apparently happens because I am given the groups on a world level again. So if I give myself these two groups in the global context that LuckPerms has, the first time I go through the AuthMe login mechanism I get the same groups in the "world" context (name of the world I'm currently in).
This is certainly another issue but seriously wtf?, and why would I get unloggedin group the opposite from what I want? I'll create another bug for this.

Given this weird behavior @xcamnhamx could we ask you to configure AuthMe with `logLevel: 'DEBUG'` and to share a log similar to the one in the image above? It might indicate what the underlying issue is.
