### ISSUE TITLE
Change HASH encryption system

### ISSUE THREAD

**Issue by StoreMaker** [AuthMe/AuthMeReloaded#1290]
Hello,
I just want to ask if there is possibility to change the HASH encryption system from SHA256 to Xenforo without losing the passwords of players, I have AuthMe connected to MySQL.

**Comment by sgdc3** [comment]
Just use this settings:

```YAML
        # Possible values: SHA256, BCRYPT, BCRYPT2Y, PBKDF2, SALTEDSHA512, WHIRLPOOL,
        # MYBB, IPB3, PHPBB, PHPFUSION, SMF, XENFORO, XAUTH, JOOMLA, WBB3, WBB4, MD5VB,
        # PBKDF2DJANGO, WORDPRESS, ROYALAUTH, CUSTOM (for developers only). See full list at
        # https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/hash_algorithms.md
        passwordHash: 'Xenforo'
        # If a password check fails, AuthMe will also try to check with the following hash methods.
        # Use this setting when you change from one hash method to another.
        # AuthMe will update the password to the new hash. Example:
        # legacyHashes:
        # - 'SHA1'
        legacyHashes:
            - 'SHA256'
```
