### ISSUE TITLE
more permissions

### ISSUE THREAD

**Issue by mat41997** [AuthMe/AuthMeReloaded#1377]
add more permissins to better configuration plugin

https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/config.md
https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/permission_nodes.md

```
settings:
    sessions:
        # Do you want to enable the session feature?
        # If enabled, when a player authenticates successfully,
        # his IP and his nickname is saved.
        # The next time the player joins the server, if his IP
        # is the same as last time and the timeout hasn't
        # expired, he will not need to authenticate.
        enabled: false
        # After how many minutes should a session expire?
        # A player's session ends after the timeout or if his IP has changed
        timeout: 10
```
e.g
# to enable session for player or group have this permission
- authme.custom.session
# to set timeout time for player or group have this permission
- authme.custom.session.timeout.10minutes

```
    restrictions:
        # Can not authenticated players chat?
        # Keep in mind that this feature also blocks all commands not
        # listed in the list below.
        allowChat: false
        # Hide the chat log from players who are not authenticated?
        hideChat: false
```
# allow chat for player or group have this permission
- authme.custom.restriction.allowchat
# hide chat for player or group have this permission
- authme.custom.restriction.hidechat

and more, or more..
