### ISSUE TITLE
API: Authme email integration

### ISSUE THREAD

**Issue by SuperJogosDBZ** [AuthMe/AuthMeReloaded#1448]
I want to put a plugin that forces the player to register his email on the server, however to do this I need to see and check registered email, can you tell me how can I do this?

**Comment by ljacqu** [comment]
This is covered by our email registration case.

In your config.yml:
```yaml
    registration:
[...]
        force: true
        # Type of registration: PASSWORD or EMAIL
        # PASSWORD = account is registered with a password supplied by the user;
        # EMAIL = password is generated and sent to the email provided by the user.
        # More info at https://github.com/AuthMe/AuthMeReloaded/wiki/Registration
        type: 'EMAIL'
```
