### ISSUE TITLE
Count-Down support for commands.yml file commands.

### ISSUE THREAD

**Issue by Pluginsel** [AuthMe/AuthMeReloaded#1449]
Can you add count-down support for commands.yml file commands?

 ```
onLogin:
  wait 3 seconds
   welcome:
     command: 'msg %p Welcome back!'
     executor: PLAYER
```
