### ISSUE TITLE
Add additional level to message keys 

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1467]
As our YML message files are growing we need to ensure that the file stays maintainable. Currently we group messages with a YAML comment but this is troublesome when we manipulate YML files. It would be easiest if we changed the message keys to have their group as first level.

Currently we have:
```yml
# Login
usage_log: '&cUsage: /login <password>'
wrong_pwd: '&cWrong password!'
```

And after introducing a path in the key:
```yml
login:
    usage_log: '&cUsage: /login <password>'
    wrong_pwd: '&cWrong password!'
```

This would automatically solve #1087.

### Task
- Change message keys to new structure
- Implement a migration for old files
- Improve key names whenever possible (since we are changing the keys anyway)
- Change all placeholders to have the format `%placeholder%`
