### ISSUE TITLE
In the last build (#2138) disrupted work the "sessions"

### ISSUE THREAD

**Issue by Roper89** [AuthMe/AuthMeReloaded#1650]
In the last build (#2138) disrupted work the "sessions"
The function no longer works:

```
settings:
    sessions:
        # Do you want to enable the session feature?
        # If enabled, when a player authenticates successfully,
        # his IP and his nickname is saved.
        # The next time the player joins the server, if his IP
        # is the same as last time and the timeout hasn't
        # expired, he will not need to authenticate.
        enabled: true
        # After how many minutes should a session expire?
        # A player's session ends after the timeout or if his IP has changed
        timeout: 10
```
Minecraft Versions: 1.12.2

**Comment by sgdc3** [comment]
@Y3cy it is configurable

**Comment by Roper89** [comment]
I have one server, I do not have bungee. Only AuthMeReloaded build (#2138)
On the old version 5.4.0, everything works for me.

I tested with the default settings, only included the session:

```
settings:
    sessions:
         enabled: true
         timeout: 10
```
