### ISSUE TITLE
How to Disable Email Verification Code?

### ISSUE THREAD

**Issue by clarkkentz** [AuthMe/AuthMeReloaded#1794]
Is there a way to disable this feature?

**Comment by ljacqu** [comment]
Do you mean the code on password reset? Yes, you can disable it in your config.yml:
```yml
    recoveryCode:
        # Number of characters a recovery code should have (0 to disable)
        length: 8
```
