### ISSUE TITLE
Authme won't hook to authmebungee

### ISSUE THREAD

**Issue by TheGameSpider** [AuthMe/AuthMeReloaded#2003]
### What behaviour is observed:
After logging in, I cannot use any commands or write chat messages, after setting chatRequiresAuth and commands: requireAuth to false, autoLogin to true, I can use commands but I need to login on each server. BungeeCord hook is set to true on each server.

### What behaviour is expected:
After logging in on my auth server, it should automatically log me in on every server.

### Steps/models to reproduce:
Install papermc 1.12.2, latest bungeecord, authme 5.6.0 b2373, latest authmebungee-2.2.0-snapshot.

### Plugin list:
plugins: authme, essentials, essentialschat, essentialsgeoip, essentialsprotect, essentialsspawn, fastlogin, multiverse-core, permissionsex, pingplayer, placeholderapi, playerpoints, plugman, protocollib, residence, skinsrestorer, supervanish, vault, viaversion, worldguard

authserver plugins: authme, essentialsspawn, fastlogin, protocollib, viaversion.

bungee plugins: authmebungee, fastlogin

### Environment description
bungeecord, auth server, other servers, authme with mysql database.
Logging in with premium account with after using `/cracked` command.

### AuthMe build number:
b2373

### Error Log:
No errors

### Configuration:
**authmebungee:**
```
authServers: 
- lobby
allServersAreAuthServers: false
commands:
    requireAuth: false
    whitelist: 
  - login, register, etc
chatRequiresAuth: false
serverSwitch:
    requiresAuth: false
    kickMessage: Authentication required.
autoLogin: true
sendOnLogout: false
unloggedUserServer: ''
```

**authme:**
sessions disabled
Hooks:
```
Hooks:
    # Do we need to hook with multiverse for spawn checking?
    multiverse: true
    # Do we need to hook with BungeeCord?
    bungeecord: true
    # Send player to this BungeeCord server after register/login
    sendPlayerTo: 'economy'
    # Do we need to disable Essentials SocialSpy on join?
    disableSocialSpy: false
    # Do we need to force /motd Essentials command on join?
    useEssentialsMotd: false
```
