### ISSUE TITLE
Question (or feature request) -> Delay to send player on another server

### ISSUE THREAD

**Issue by Volgeop** [AuthMe/AuthMeReloaded#2116]
Hi, how could I teleport player after login and specific delay (for ex. 20 seconds) to Lobby? I can't use this option in Config, because there I can't set delay... maybe it could be added?
```
    bungeecord: true
    # Send player to this BungeeCord server after register/login
    sendPlayerTo: '' #Missing delay option
```
So I tried use something like this:
```
onLogin:
  lobby:
    command: 'send %p Lobby' #But this command didn't work, because it's bungee and after execute it says that command doesn't exist...
    executor: CONSOLE
    delay: 400 
```

Try 2:
```
onLogin:
  lobby:
    command: 'server Lobby' #But this command didn't work, because it's bungee and after execute it says that command doesn't exist...
    executor: PLAYER
    delay: 400 
```

Try 3:
I found just one solution, but I'd rather have another....
```
onLogin:
  lobby:
    command: 'minecraft:tp %p -22 72 -14' #Teleport into Portal...
    executor: CONSOLE
    delay: 400
```

So... My question is, if I could normally teleport player into specific server with any delay? And if not, could it be added into normal authme config under this option?
```
    bungeecord: true
    # Send player to this BungeeCord server after register/login
    sendPlayerTo: '' #Missing delay option
```

Or could someone give me better command to commands.yml, so I won't have to use teleport to portal, but any better way?

Thanks for reading, hoping for help.
