### ISSUE TITLE
Command.yml Executer: Console its working wrongly

### ISSUE THREAD

**Issue by OverBrave** [AuthMe/AuthMeReloaded#2130]
### What behaviour is observed:
What happened?
```
onLogin:
   scnpc:
     command: "openbook bilgi %p"
     executer: CONSOLE
```

But it makes the executor see him as a player and says "You have no permission to do this." message is coming to player.

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Bungeecord server, one lobby server, MySQL

### AuthMe build number:
![image](https://user-images.githubusercontent.com/47111280/84324973-69f54000-ab82-11ea-8827-e3265354890e.png)
