### ISSUE TITLE
Configurating commands.yml

### ISSUE THREAD

**Issue by iamdoms** [AuthMe/AuthMeReloaded#2162]
When I changed the join message from nothing to `§l[§a§l+§f§l] §a%p` my server has been crashed and I cant start it.

### What behaviour is expected:
a join message: [+] {the player's name}

### Steps/models to reproduce:
In commands.yml, replace it with these:
```yml
# This configuration file allows you to execute commands on various events.
# Supported placeholders in commands:
#   %p is replaced with the player name.
#   %nick is replaced with the player's nick name
#   %ip is replaced with the player's IP address
#   %country is replaced with the player's country
# 
# For example, if you want to send a welcome message to a player who just registered:
# onRegister:
#   welcome:
#     command: 'msg %p Welcome to the server!'
#     executor: CONSOLE
# 
# This will make the console execute the msg command to the player.
# Each command under an event has a name you can choose freely (e.g. 'welcome' as above),
# after which a mandatory 'command' field defines the command to run,
# and 'executor' defines who will run the command (either PLAYER or CONSOLE). Longer example:
# onLogin:
#   welcome:
#     command: 'msg %p Welcome back!'
#     executor: PLAYER
#   broadcast:
#     command: 'broadcast %p has joined, welcome back!'
#     executor: CONSOLE
# 
# Supported command events: onLogin, onSessionLogin, onJoin, onLogout, onRegister, onUnregister
onJoin: {}
onLogin: {§l[§a§l+§f§l] §a%p}
# These commands are called whenever a logged in player uses /logout or quits.
# The commands are not run if a player that was not logged in quits the server.
# Note: if your server crashes, these commands won't be run, so don't rely on them to undo
# 'onLogin' commands that would be dangerous for non-logged in players to have!
onLogout: {§l[§c§l+§f§l] §c%p}
onRegister: {§l[§2§l+§f§l] §2%p}
onSessionLogin: {}
# Commands to run whenever a player is unregistered (by himself, or by an admin)
onUnregister: {§l[§4§l+§f§l] §4%p}
```

### Plugin list:
I don't have permission to /pl, but I have the FTP: 
![image](https://user-images.githubusercontent.com/63553775/88215328-c3f62480-cc5b-11ea-9a3e-252bdc978abf.png)

### Environment description
Spigot 1.12.2

### AuthMe build number:
I can't join to the server, so I don't know.

### Configuration:
Already wrote in "Steps to reproduce"

**Comment by ljacqu** [comment]
The commands.yml is for _commands_; please follow the template:
```yml
# onLogin:
#   welcome:
#     command: 'msg %p Welcome back!'
#     executor: PLAYER
#   broadcast:
#     command: 'broadcast %p has joined, welcome back!'
#     executor: CONSOLE
```

so e.g. something like
```yml
onLogin:
  command: 'ping {§l[§a§l+§f§l] §a%p}'
  executor: PLAYER
```

To use Essentials' /ping to display messages, for example.
