### ISSUE TITLE
GroupOptions (registeredPlayerGroup) doesn't work with LuckPerms

### ISSUE THREAD

**Issue by MobButcher** [AuthMe/AuthMeReloaded#2308]
### What behaviour is observed:
When setting up AuthMe Extended, I tried to configure the GroupOptions settings to strip away all of the permissions and force users into `notlogged` group while they are in the unlogged-in limbo. Unfortunately, it doesn't work: it strips away all of the other permission groups, but it does not add the one configured in the AuthMe's config.

### What behaviour is expected:
When configured as shown below, when person is not logged in, they have only two LuckPerms groups assigned: default and `notlogged`.

### Steps/models to reproduce:
Set up as listed below; log out and log back in (without session).

### Plugin list:
`Vault`, `LuckPerms`, `AuthMe`.

### Environment description
Standalone server on Purpur 1.16.5 build 1038 (fork of Paper), no SQL.

### AuthMe build number:
v5.6.0 snapshot, build 2448
LuckPerms v5.3.3

### Error Log:
None.

### Configuration:
```
AuthMe:
GroupOptions:
    enablePermissionCheck: true
    registeredPlayerGroup: 'notlogged'
    unregisteredPlayerGroup: 'notlogged'
    unLoggedInGroup: 'notlogged'

LuckPerms:
storage-method: YAML

notlogged.yml:
name: notlogged
permissions:
- authme.player.*
- '*':
    value: false
- essentials.motd
```
