### ISSUE TITLE
Multiple Encryption

### ISSUE THREAD

**Issue by troke12** [AuthMe/AuthMeReloaded#2338]
I was thinking for more better security, and this is the workflow for multiple encryption

`config.yml`

```yaml
# MultipleEncryption
EnableMultipleEncryption: true
EncrytionFirst: MD5
EncryptionTwo: BCRYPT

# if the MultipleEncryption enabled it will disabled this
passwordHash: BCRYPT
```

![image](https://user-images.githubusercontent.com/10250068/118385430-3dbf2a80-b641-11eb-88a8-4f7f1a90c779.png)

i dont know if this possible or not, just suggestion
