### ISSUE TITLE
EssentialsX's spawn location is not being parsed properly

### ISSUE THREAD

**Issue by vitaly-rudenko** [AuthMe/AuthMeReloaded#2524]
### What behaviour is observed?

AuthMe doesn't teleport unlogged user to EssentialsX spawn location

### Expected behaviour

AuthMe should teleport unlogged user to EssentialsX spawn location

Not sure, but the problem might be that EssentialsX now stores spawn location like this:
```yml
spawns:
  default:
    world: abcbf397-321f-4746-a6c8-ca54bb81b882
    world-name: world
    x: 0.5
    y: 115.0
    z: 0.5
    yaw: 0
    pitch: 0
```

While AuthMe uses `world` as if it was `worldName`:
https://github.com/AuthMe/AuthMeReloaded/blob/5c83f5e26169eb60eb0f411dc7530e675e84c6af/src/main/java/fr/xephi/authme/settings/SpawnLoader.java#L290

In any case, you can use `EssentialSpawn` class to get spawn location without parsing `spawn.yml` file:
```java
essentialsSpawn.getSpawn("default");
```

### To Reproduce

1. Set EssentialsX spawn to Overworld
2. Log out while in Nether
3. Log in
4. Observer yourself in Nether's default spawn

### Plugin list

EssentialsX (latest)
AuthMeReloaded (latest)

### Server Implementation

Standalone server (no proxy)

### Database Implementation

MySQL

### AuthMe Version

AuthMeReloaded v5.6.0-SNAPSHOT (build: 2517)

### Configuration

https://paste.gg/p/anonymous/cc6f9ae682b749789ab556c1a1291f25
